(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'str' object is not callable"
p3
sS'layer'
p4
S'/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py'
p5
sS'code'
p6
S'<code object <module> at 0xae6c99f8, file "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 5>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/topf/Web2Py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 275, in <module>\n  File "/home/topf/Web2Py/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 17, in index_helper\n    response.flash(\'Data received!\')\nTypeError: \'str\' object is not callable\n'
p11
s.